-- Subscribers and the admin audit trail (BE-07, Section 8.1, ADR-11). Portable SQL for H2 and PostgreSQL.
-- Ids are UUIDs generated by the application; times are UTC instants.

-- Generic subscriber: the subscriber type plugin gives meaning to display_name and address.
CREATE TABLE subscriber (
    id                  UUID                        NOT NULL,
    type                VARCHAR(32)                 NOT NULL,
    display_name        VARCHAR(200),                           -- name, or the optional label of a webhook
    address             VARCHAR(1024)               NOT NULL,   -- email in plain form; secret addresses encrypted (BE-09)
    address_fingerprint VARCHAR(64)                 NOT NULL,   -- keyed HMAC of the normalised address
    address_masked      VARCHAR(200)                NOT NULL,   -- safe to show in the UI and logs
    status              VARCHAR(16)                 NOT NULL,
    subscribed_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status_changed_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_subscriber PRIMARY KEY (id),
    -- One subscription per address, for every type (FR-05).
    CONSTRAINT uq_subscriber_address_fingerprint UNIQUE (address_fingerprint),
    CONSTRAINT ck_subscriber_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- Admin list (FR-25, FR-26): ordered by subscription date, searched by name and email address.
CREATE INDEX ix_subscriber_subscribed_at ON subscriber (subscribed_at, id);
CREATE INDEX ix_subscriber_display_name ON subscriber (display_name);
CREATE INDEX ix_subscriber_address ON subscriber (address);
-- Delivery: the active subscribers of a type.
CREATE INDEX ix_subscriber_status_type ON subscriber (status, type);

-- Admin actions (FR-30). No personal data of the affected subscriber, only its type.
CREATE TABLE audit_entry (
    id              UUID                        NOT NULL,
    admin_email     VARCHAR(320)                NOT NULL,
    action          VARCHAR(32)                 NOT NULL,
    subscriber_type VARCHAR(32)                 NOT NULL,
    performed_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_audit_entry PRIMARY KEY (id),
    CONSTRAINT ck_audit_entry_action CHECK (action IN ('SUBSCRIBER_DELETED'))
);

-- Retention (Section 8.4) deletes audit entries by age.
CREATE INDEX ix_audit_entry_performed_at ON audit_entry (performed_at);
