-- Runs, collected events, source state and notifications (BE-08, Section 8.1, 8.2, ADR-06).
-- Portable SQL for H2 and PostgreSQL. Ids are UUIDs generated by the application; times are UTC instants.

-- One collection and delivery run (FR-11, NFR-16).
CREATE TABLE run (
    id            UUID                        NOT NULL,
    run_trigger   VARCHAR(16)                 NOT NULL,   -- "trigger" in Section 8.1; renamed, TRIGGER is an SQL keyword
    status        VARCHAR(16)                 NOT NULL,
    started_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    finished_at   TIMESTAMP(6) WITH TIME ZONE,
    new_events    INT                         NOT NULL,
    sent          INT                         NOT NULL,
    failed        INT                         NOT NULL,
    error_summary VARCHAR(2000),
    CONSTRAINT pk_run PRIMARY KEY (id),
    CONSTRAINT ck_run_trigger CHECK (run_trigger IN ('SCHEDULED', 'MANUAL', 'CATCH_UP')),
    CONSTRAINT ck_run_status CHECK (status IN ('RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'SKIPPED'))
);

-- Run history (newest first) and retention by age.
CREATE INDEX ix_run_started_at ON run (started_at);

-- Result of one source within a run. Deleted together with its run.
CREATE TABLE run_source_result (
    run_id        UUID          NOT NULL,
    source_key    VARCHAR(64)   NOT NULL,
    status        VARCHAR(16)   NOT NULL,
    attempts      INT           NOT NULL,
    new_events    INT           NOT NULL,
    error_summary VARCHAR(2000),
    CONSTRAINT pk_run_source_result PRIMARY KEY (run_id, source_key),
    CONSTRAINT fk_run_source_result_run FOREIGN KEY (run_id) REFERENCES run (id) ON DELETE CASCADE,
    CONSTRAINT ck_run_source_result_status CHECK (status IN ('COMPLETED', 'FAILED'))
);

-- Runtime state per configured source (the sources themselves are configuration, FR-33).
CREATE TABLE source_state (
    source_key      VARCHAR(64)                 NOT NULL,
    last_success_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_source_state PRIMARY KEY (source_key)
);

-- An event in the standard format (CON-05, FR-09). event_key is the idempotency key (FR-10).
CREATE TABLE event (
    id           UUID                        NOT NULL,
    event_key    VARCHAR(255)                NOT NULL,
    source_key   VARCHAR(64)                 NOT NULL,   -- plugin key, e.g. newsapi
    source_name  VARCHAR(200)                NOT NULL,   -- human-readable source, e.g. BBC News (FR-09, FR-17)
    title        VARCHAR(500)                NOT NULL,
    content      VARCHAR(4000)               NOT NULL,
    link         VARCHAR(2048),
    occurred_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    collected_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    run_id       UUID                        NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT uq_event_event_key UNIQUE (event_key),
    CONSTRAINT fk_event_run FOREIGN KEY (run_id) REFERENCES run (id)
);

-- Retention by age (Section 8.4) and the events of a run.
CREATE INDEX ix_event_collected_at ON event (collected_at);
CREATE INDEX ix_event_run_id ON event (run_id);

-- One message for one event and one subscriber (ADR-06). subscriber_id has no foreign key on purpose: the
-- history keeps the opaque id after the subscriber is deleted (Section 8.2).
CREATE TABLE notification (
    id              UUID                        NOT NULL,
    event_id        UUID                        NOT NULL,
    subscriber_id   UUID                        NOT NULL,
    run_id          UUID                        NOT NULL,
    channel_key     VARCHAR(64)                 NOT NULL,
    status          VARCHAR(16)                 NOT NULL,
    attempts        INT                         NOT NULL,
    next_attempt_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    lease_until     TIMESTAMP(6) WITH TIME ZONE,
    error_reason    VARCHAR(1000),
    sent_at         TIMESTAMP(6) WITH TIME ZONE,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,   -- not in Section 8.1; needed for retention by age
    CONSTRAINT pk_notification PRIMARY KEY (id),
    -- An event is never scheduled twice for the same subscriber (FR-20).
    CONSTRAINT uq_notification_event_subscriber UNIQUE (event_id, subscriber_id),
    CONSTRAINT fk_notification_event FOREIGN KEY (event_id) REFERENCES event (id),
    CONSTRAINT fk_notification_run FOREIGN KEY (run_id) REFERENCES run (id),
    CONSTRAINT ck_notification_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'SENT', 'FAILED', 'CANCELLED'))
);

-- Delivery: claimable notifications per channel (PENDING and due) ...
CREATE INDEX ix_notification_claim ON notification (status, channel_key, next_attempt_at);
-- ... and IN_PROGRESS notifications whose lease has expired.
CREATE INDEX ix_notification_lease ON notification (status, lease_until);
-- Deleting a subscriber removes its PENDING notifications (Section 8.2).
CREATE INDEX ix_notification_subscriber ON notification (subscriber_id, status);
-- Run statistics and retention by age.
CREATE INDEX ix_notification_run_id ON notification (run_id);
CREATE INDEX ix_notification_created_at ON notification (created_at);
